### ISSUE TITLE
Access8Math - Documentation update broken in svn2addon direction

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/mrconfig#68] opened 2022-01-03 10:58 UTC
For Access8Math, the website documentation has been updated for French and Spanish (maybe also other languages).
However it has not been updated in the stable branch of nvdaaddons/Access8Math repo.
I have not looked at other add-ons to see if they suffer from the same issue.

@feerrenrut could you have a look at it please when you're back? Thanks.

Cc @tsengwoody, author of Access8Math add-on.

**Comment by jmdaweb** [comment] 2022-03-30 08:10
I opened issue #72 without looking at this one first, but seems that the problem is the same. At least, Access8math has documentation. Proxy and updateChannel are in a worse state.

**Comment by CyrilleB79** [comment] 2022-03-30 13:00
Ping @feerrenrut for this issue and #72.

Could you please have a look at it in the coming days? Since it is the period where people should upgrade compatibility with 2022.1:
* some people are waiting for this update to release their add-on
* maybe some others release their add-on missing the last translation work
Thanks.

**Comment by jmdaweb** [comment] 2022-04-01 07:43
Hi,
I have just received documentation updates for Golden Cursor, so we can confirm that this isn't a general problem for all add-ons.
Regards.

**Comment by michaelDCurran** [comment] 2022-04-05 07:36
I noticed that both Access8Math and directLink addons had uncommitted changes in their git repos on our server. Specifically nvda.po for ru, zh_CN and zh_TW for access8Math.
These uncommitted changes were to strip the file path comments from the po files. This is automatically done by our gitconfig, but at some point (possibly due to a server upgrade several months aback) git may have been run under the wrong account and therefore the correct config was not used.
I have committed these changes to stable and re-run cron jobs for these two addons.
Let me know if the issue has been addressed.

**Comment by CyrilleB79** [comment] 2022-04-06 15:25
For Access8Math, maybe the impacted languages are the ones which have been merged via direct PRs in the repo rather than via the translation framework.
@tsengwoody, would you be able to confirm this or not?

**Comment by tsengwoody** [comment] 2022-04-07 01:49
> For Access8Math, maybe the impacted languages are the ones which have been merged via direct PRs in the repo rather than via the translation framework.

I merge and update impacted languages zh_TW

**Comment by feerrenrut** [comment] 2022-05-16 05:29
It sounds like this is resolved. I'm going to close this issue. Please open a new issue if there are still issues.

**Closed as completed by feerrenrut** 2022-05-16 05:29 UTC
